services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile # Cambia a Dockerfile.dev para desarrollo
    ports:
      - "80:80" # Cambia a "4200:4200" y "49153:49153" para desarrollo
    environment:
      - NODE_ENV=production # Cambia a development para desarrollo
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules
    #   (Descomenta para desarrollo: hot reload)
    command: ["nginx", "-g", "daemon off;"] # Cambia a "npm run start" para desarrollo

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile # Cambia a Dockerfile.dev para desarrollo
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production # Cambia a development para desarrollo
      - SECRET_JWT_KEY=${SECRET_JWT_KEY}
    # volumes:
    #   - ./backend:/app
    #   - /app/node_modules
    #   (Descomenta para desarrollo: hot reload)
    command: ["node", "dist/main.js"] # Cambia a "npm run start:dev" para desarrollo
